### ISSUE TITLE
ABE Pilot Launch 🚀

### ISSUE THREAD

**Issue by countvajhula** [drym-org/symex.el#111]
Dear Symex friends, 🐿️ 
We recently concluded the process of [DIA for Symex](https://github.com/drym-org/dia-symex), and the results include the list of people who are eligible to receive [shares of financial contributions](https://github.com/drym-org/symex.el/blob/master/abe/attributions.txt) made to the Symex project, in accordance with [Attribution Based Economics](https://github.com/drym-org/foundation).

I'm pleased to report that we are getting close on the initial launch of the accounting prototype, [Old Abe](https://github.com/drym-org/old-abe), which will manage accounting for projects according to the ABE financial model. In order to give you your share, I will need your payment information. So please email me at skasivaj at gmail dot com with your preferred way to receive payment, for example:

- Venmo id
- Paypal email
- anything else

Here are some contributors for whom I _do not_ have payment information:

@polaris64 @jefftrull @tommy-mor @markgdawson @riscy @j-shilling @doyougnu @pepperblue @anonimitoraf @dcostaras 

Please send me this information by **Thursday**, if possible, as that is the day on which we are planning to execute initial payments.

It has been a lot of work to get to this initial stage and it's easy to miss the forest for the trees, so I'd like to take this moment to say: _Your contributions have been valuable. They are appreciated by many_. Thank you.

Learn more about Attribution Based Economics:

[The talk introducing it at EmacsConf](https://www.youtube.com/watch?v=1WIulCmIHZ4)
The [Extended Q&A](https://emacsconf.org/2022/talks/maint/) covering a lot of questions about the implementation and goals
The [ABE Financial Model](https://drym-org.github.io/foundation/)

See also the companion issues on the other repos in the pilot:

[ABE Pilot Launch](https://github.com/drym-org/old-abe/issues/19) (Old Abe)
[ABE Pilot Launch](https://github.com/drym-org/qi/issues/97) (Qi)

**Comment by tommy-mor** [comment]
sent you an email with my venmo

**Comment by countvajhula** [comment]
@tommy-mor Got it, thanks!

**Comment by doyougnu** [comment]
Hello! I've sent you an email

**Comment by riscy** [comment]
Hi @countvajhula - I'm surprised and honored to be on this list!  I realize I am a little late in my response here, but whatever share you intended on sending my way I would be happy to see spread among the other contributors and/or passed along to other projects.

**Comment by pepperblue** [comment]
Good morning @countvajhula - I'm also surprised and a little late :innocent:
Please use my part of the share to do whatever makes sense to you ...
Sunny greetings :sun_with_face:

**Comment by dcostaras** [comment]
Hi @countvajhula, apologies I've also only just seen this now. If you don't mind I'm going to pause engaging with this for a bit as I'm interested in what you're doing here (even though I don't think my contributions have been valuable) but am pressed for time at the moment.

**Comment by countvajhula** [comment]
Hey everyone - another update. It's been a bit more work than we anticipated to iron out all the kinks for launch. We're looking at sometime next week, and I'll keep you updated. Take care!

**Comment by countvajhula** [comment]
We successfully launched recently, see [this announcement](https://groups.google.com/g/abe-congress/c/lePqH8ZJUr8) for the full update (and join the mailing list if you'd like to follow further updates).

Thanks all!
